- name: sample palybook
  hosts: local
  connection:local
  tasks:
  - name: print hello world
    ansible.builtin.debug:
     msg: "hello world"

  tasks:
  - name: print 
    ansible.builtin.debug:
     msg: "This is tessy"
        
    
 